import Head from 'next/head'
import { motion as m } from 'framer-motion'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<m.div
				initial={{ opacity: 0 }}
				animate={{ opacity: 1 }}
				transition={{ duration: 0.75, ease: 'easeOut' }}
				exit={{ opacity: 0 }}
				className='h-full flex flex-col'
			>
				<div
					className='flex flex-1 items-center justify-end'
				>
					<h1 className='font-rubik text-8xl text-right uppercase tracking-[20px] leading-snug'>
						Front-End <br /> <strong>Developer</strong>
					</h1>
				</div>
				<h3 className='flex text-2xl justify-end text-right gap-10 font-alef'>
					FrontEnd <span>&</span> DataScience
				</h3>
			</m.div>
		</>
	)
}
